version: "3.7"

services:
  app:
    build: .
    container_name: integration-pipedrive-bling
    ports: 
      - 9090:9090
    volumes:
      - .:/usr/app
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "linkapi-teste"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot


